#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <limine.h>
#include <string.h>
#include <stdio.h>
#include <video.h>

static void hcf(void) {
  for(;;) {
    asm ("hlt");
  }
}



void kmain(void) {

  video_init();

  kprintf("Hello World! So happy to see everyone from here.");
  kprintf(
    "line 01: scrolling test\n"
    "line 02: scrolling test\n"
    "line 03: scrolling test\n"
    "line 04: scrolling test\n"
    "line 05: scrolling test\n"
    "line 06: scrolling test\n"
    "line 07: scrolling test\n"
    "line 08: scrolling test\n"
    "line 09: scrolling test\n"
    "line 10: scrolling test\n"
    "line 11: scrolling test\n"
    "line 12: scrolling test\n"
    "line 13: scrolling test\n"
    "line 14: scrolling test\n"
    "line 15: scrolling test\n"
    "line 16: scrolling test\n"
    "line 17: scrolling test\n"
    "line 18: scrolling test\n"
    "line 19: scrolling test\n"
    "line 20: scrolling test\n"
    "line 21: scrolling test\n"
    "line 22: scrolling test\n"
    "line 23: scrolling test\n"
    "line 24: scrolling test\n"
    "line 25: scrolling test\n"
    "line 26: scrolling test\n"
    "line 27: scrolling test\n"
    "line 28: scrolling test\n"
    "line 29: scrolling test\n"
    "line 30: scrolling test\n"
    "line 01: scrolling test\n"
    "line 02: scrolling test\n"
    "line 03: scrolling test\n"
    "line 04: scrolling test\n"
    "line 05: scrolling test\n"
    "line 06: scrolling test\n"
    "line 07: scrolling test\n"
    "line 08: scrolling test\n"
    "line 09: scrolling test\n"
    "line 10: scrolling test\n"
    "line 11: scrolling test\n"
    "line 12: scrolling test\n"
    "line 13: scrolling test\n"
    "line 14: scrolling test\n"
    "line 15: scrolling test\n"
    "line 16: scrolling test\n"
    "line 17: scrolling test\n"
    "line 18: scrolling test\n"
    "line 19: scrolling test\n"
    "line 20: scrolling test\n"
    "line 21: scrolling test\n"
    "line 22: scrolling test\n"
    "line 23: scrolling test\n"
    "line 24: scrolling test\n"
    "line 25: scrolling test\n"
    "line 26: scrolling test\n"
    "line 27: scrolling test\n"
    "line 28: scrolling test\n"
    "line 29: scrolling test\n"
    "line 30: scrolling test\n"
    "line 01: scrolling test\n"
    "line 02: scrolling test\n"
    "line 03: scrolling test\n"
    "line 04: scrolling test\n"
    "line 05: scrolling test\n"
    "line 06: scrolling test\n"
    "line 07: scrolling test\n"
    "line 08: scrolling test\n"
    "line 09: scrolling test\n"
    "line 10: scrolling test\n"
    "line 11: scrolling test\n"
    "line 12: scrolling test\n"
    "line 13: scrolling test\n"
    "line 14: scrolling test\n"
    "line 15: scrolling test\n"
    "line 16: scrolling test\n"
    "line 17: scrolling test\n"
    "line 18: scrolling test\n"
    "line 19: scrolling test\n"
    "line 20: scrolling test\n"
    "line 21: scrolling test\n"
    "line 22: scrolling test\n"
    "line 23: scrolling test\n"
    "line 24: scrolling test\n"
    "line 25: scrolling test\n"
    "line 26: scrolling test\n"
    "line 27: scrolling test\n"
    "line 28: scrolling test\n"
    "line 29: scrolling test\n"
    "line 30: scrolling test\n"
    "line 01: scrolling test\n"
    "line 02: scrolling test\n"
    "line 03: scrolling test\n"
    "line 04: scrolling test\n"
    "line 05: scrolling test\n"
    "line 06: scrolling test\n"
    "line 07: scrolling test\n"
    "line 08: scrolling test\n"
    "line 09: scrolling test\n"
    "line 10: scrolling test\n"
    "line 11: scrolling test\n"
    "line 12: scrolling test\n"
    "line 13: scrolling test\n"
    "line 14: scrolling test\n"
    "line 15: scrolling test\n"
    "line 16: scrolling test\n"
    "line 17: scrolling test\n"
    "line 18: scrolling test\n"
    "line 19: scrolling test\n"
    "line 20: scrolling test\n"
    "line 21: scrolling test\n"
    "line 22: scrolling test\n"
    "line 23: scrolling test\n"
    "line 24: scrolling test\n"
    "line 25: scrolling test\n"
    "line 26: scrolling test\n"
    "line 27: scrolling test\n"
    "line 28: scrolling test\n"
    "line 29: scrolling test\n"
    "line 30: scrolling test\n"
  );
  hcf();
}

